---
abstract: 'AnyEvent HTTP/1.1 Server'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-HTTP-Server
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 5
  Digest::SHA1: 2
  JSON::XS: 3
version: 1.9998
